name: riscv-toolchain

on:
  push:
  pull_request:

jobs:
  build_rv32i:
    runs-on: ubuntu-latest

    steps:
#     - name: Checkout riscv-toolchain
#       run: git clone --depth 1 --recursive https://github.com/riscv/riscv-gnu-toolchain

    - name: Install build dependencies
      run: sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev

    - name: Checkout riscv-gcc
      run: git clone --depth 1 https://github.com/riscv/riscv-gcc
      
    - name: Configure
      run: |
        mkdir build
        cd build
        ../riscv-gcc/configure \
          --prefix=/opt/riscv/rv32i \
          --host=x86_64-linux-gnu \
          --target=riscv64-linux-gnu \
          --enable-languages=c \
          --disable-shared --disable-threads \
          --disable-libssp --disable-libmudflap \
          --disable-libitm --disable-libsanitizer \
          --disable-libgomp --disable-nls \
          --disable-libquadmath --disable-libquadmath-support \
          --disable-multilib \
          --enable-multiarch \
          --with-arch=rv32i --with-abi=ilp32 \
          --program-prefix=riscv32-none-elf-
      
    - name: Compile
      working-directory: build
      run: make -j4
      
    - name: Install
      working-directory: build
      run: make install
      
    - name: Result
      run: find /opt/riscv/rv32i
      
    - name: Tar
      run: tar -C /opt/riscv -cJf rv32i.tar.xz rv32i
      
    - uses: actions/upload-artifact@v2
      with:
        name: rv32i
        path: rv32i.tar.xz 
      
