name: riscv-toolchain

on:
  push:
  pull_request:

jobs:
  build_rv32i:
    runs-on: ubuntu-latest
    env:
      MARCH: "rv32i"
      MABI: "ilp32"
      TARGET: "riscv32-unknown-elf"
      PREFIX: "/opt/riscv/rv32i"

    steps:
#     - name: Checkout riscv-toolchain
#       run: git clone --depth 1 --recursive https://github.com/riscv/riscv-gnu-toolchain

    - name: Install build dependencies
      run: sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev

    - name: Checkout riscv-gcc
      uses: actions/checkout@v2
      with:
        repository: riscv/riscv-gcc
        path: riscv-gcc
      
    - name: Checkout riscv-binutils
      uses: actions/checkout@v2
      with:
        repository: riscv/riscv-binutils-gdb
        path: riscv-binutils-gdb
      
    - name: Show build environment
      run: |
        echo $PREFIX
        echo $TARGET
        echo $PATH
        gcc -v
        
    - name: Configure binutils
      run: |
        export PATH="$PATH:$PREFIX/bin"
        mkdir build-binutils
        cd build-binutils
        
        ../riscv-binutils-gdb/configure \
          --prefix="$PREFIX" \
          --host="x86_64-linux-gnu" \
          --target="$TARGET" \
          --with-sysroot \
          --disable-werror \
          --disable-shared \
          --disable-threads \
          --disable-plugin \
          --disable-tls \
          --disable-libmudflap \
          --disable-libssp \
          --disable-libgomp \
          --disable-nls \
          --disable-tm-clone-registry \
          --disable-libitm --disable-libsanitizer \
          --disable-libquadmath --disable-libquadmath-support \
          --disable-multilib \
          --enable-multiarch \
          --with-arch=$MARCH --with-abi=$MABI \
          --program-prefix=${TARGET}-
      
    - name: Compile binutils
      working-directory: build-binutils
      run: PATH="$PATH:$PREFIX/bin" make -j4
      
    - name: Install binutils
      working-directory: build-binutils
      run: PATH="$PATH:$PREFIX/bin" make install
      
    - name: Configure gcc
      run: |
        export PATH="$PATH:$PREFIX/bin"
        mkdir build-gcc
        cd build-gcc
        
        ../riscv-gcc/configure \
          --prefix=$PREFIX \
          --host=x86_64-linux-gnu \
          --target=$TARGET \
          --enable-languages=c \
          --disable-shared \
          --disable-threads \
          --disable-plugin \
          --disable-tls \
          --disable-libmudflap \
          --disable-libssp \
          --disable-libgomp \
          --disable-nls \
          --disable-tm-clone-registry \
          --disable-libitm --disable-libsanitizer \
          --disable-libquadmath --disable-libquadmath-support \
          --disable-multilib \
          --enable-multiarch \
          --with-arch=$MARCH --with-abi=$MABI \
          --program-prefix=${TARGET}-
      
    - name: Compile gcc
      working-directory: build-gcc
      run: PATH="$PATH:$PREFIX/bin" make -j4
      
    - name: Install gcc
      working-directory: build-gcc
      run: PATH="$PATH:$PREFIX/bin" make install
      
    - name: Generate prebuilt binary tarball
      run: tar -C $PREFIX/.. -cvJf $MARCH-$MABI.tar.xz ${PREFIX##*/}
      
    - uses: actions/upload-artifact@v2
      with:
        name: $MARCH-$MABI
        path: $MARCH-$MABI.tar.xz
      
