name: riscv-toolchain

on:
  push:
  pull_request:

jobs:
  build_rv32gc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout riscv-toolchain
      run: git clone --depth 1 --recursive https://github.com/riscv/riscv-gnu-toolchain
      
    - name: Configure
      working-directory: riscv-gnu-toolchain
      run: ./configure --prefix=/opt/riscv-rv32gc --with-arch=rv32gc --with-abi=ilp32d
      
    - name: Compile
      working-directory: riscv-gnu-toolchain
      run: make
      
    - name: Result
      run: find /opt/riscv-rv32gc
      
    - name: Tar
      run: tar -C /opt -cJf riscv-rv32gc.tar.xz riscv-rv32gc
      
    - uses: actions/upload-artifact@v2
      with:
        name: riscv-rv32gc
        path: riscv-rv32gc.tar.xz 
      
