name: riscv-toolchain

on:
  push:
  pull_request:

jobs:
  build_rv32i:
    runs-on: ubuntu-latest

    steps:
#     - name: Checkout riscv-toolchain
#       run: git clone --depth 1 --recursive https://github.com/riscv/riscv-gnu-toolchain

    - name: Checkout riscv-gcc
      run: git clone --depth 1 https://github.com/riscv/riscv-gcc
      
    - name: Configure
      working-directory: riscv-gcc
      run: |
        mkdir build
        cd build
        ../configure --prefix=/opt/riscv/rv32i \
                     --enable-languages=c \
                     --disable-libitm --disable-libsanitizer --disable-libquadmath --disable-libquadmath-support \
                     --enable-multiarch --disable-multilib \
                     --with-arch=rv32i --with-abi=ilp32 \
                     --build=x86_64-linux-gnu --host=x86_64-linux-gnu \
                     --target=riscv64-linux-gnu \
                     --program-prefix=riscv32-none-elf-
      
    - name: Compile
      working-directory: riscv-gcc/build
      run: make -j4
      
    - name: Install
      working-directory: riscv-gcc/build
      run: make install
      
    - name: Result
      run: find /opt/riscv/rv32i
      
    - name: Tar
      run: tar -C /opt/riscv -cJf rv32i.tar.xz rv32i
      
    - uses: actions/upload-artifact@v2
      with:
        name: rv32i
        path: rv32i.tar.xz 
      
